export function chatMarkup(initialMessage: string): string {
  return [
    '<section class="chat-layout"><header class="chat-head"><span class="chat-tech" aria-hidden="true"><svg viewBox="0 0 64 48" focusable="false"><path class="chat-circuit" d="M2 13h10l5 5M62 12H52l-5 5M3 40h9l5-5M61 39h-9l-5-5"/><path class="chat-mountain chat-mountain-left" d="M8 35 27 22l12 9"/><path class="chat-mountain chat-mountain-right" d="m31 30 13-11 14 16"/><circle cx="2" cy="13" r="1.8"/><circle cx="62" cy="12" r="1.8"/><circle cx="3" cy="40" r="1.8"/><circle cx="61" cy="39" r="1.8"/></svg></span>',
    '<div><strong id="chat-preview-title">Asistente SaltaCode</strong><small>Orientación sobre servicios y proyectos</small></div><button class="chat-close" type="button" aria-label="Cerrar chat">×</button></header>',
    `<div class="chat-log" role="log" aria-label="Conversación con el asistente"><article class="chat-message" data-role="agent"><p>${initialMessage}</p></article><div class="chat-suggestions" aria-label="Consultas sugeridas"><button type="button">Necesito software a medida</button><button type="button">Quiero mejorar un proceso</button><button type="button">Busco un equipo IT</button></div></div>`,
    '<form class="chat-compose"><label for="chat-preview-message">Escribí tu consulta</label><div class="chat-row"><textarea id="chat-preview-message" maxlength="4000" rows="1" placeholder="Contanos qué necesitás…"></textarea><button class="chat-send" type="submit">Enviar</button></div><div class="chat-actions"><a href="/contacto/">Contactar a una persona</a></div></form>',
    '<section class="chat-consent-gate" aria-labelledby="chat-consent-title" hidden><div class="chat-consent-card"><h2 id="chat-consent-title">Antes de iniciar el chat</h2><p>SaltaCode guardará esta conversación para responder y darle continuidad. La consulta puede ser procesada por proveedores de inteligencia artificial. Podés ejercer tus derechos según nuestra <a href="/legal/privacidad/" target="_blank" rel="noopener noreferrer">Política de privacidad</a> y conocer el almacenamiento usado en <a href="/legal/cookies/" target="_blank" rel="noopener noreferrer">Cookies</a>.</p>',
    '<p class="chat-consent-question"></p><p class="chat-sensitive"><strong>No incluyas contraseñas, credenciales ni datos sensibles.</strong></p><div class="chat-consent-actions"><button class="chat-consent-accept" type="button">Aceptar y enviar</button><button class="chat-consent-cancel" type="button">Cancelar</button></div></div></section>',
    '<p class="visually-hidden" role="status" aria-live="polite" aria-atomic="true"></p></section>',
  ].join("");
}
