"""initial agent platform

Revision ID: 9ffe2a3e79cd
Revises: None
Create Date: 2026-08-27 01:57:01.563217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '9ffe2a3e79cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector is required before SQLAlchemy creates the VECTOR columns/indexes.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_roles_is_active'), 'admin_roles', ['is_active'], unique=False)
    op.create_index(op.f('ix_admin_roles_key'), 'admin_roles', ['key'], unique=True)
    op.create_table('agent_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_identity', sa.Text(), nullable=False),
    sa.Column('prompt_domain', sa.Text(), nullable=False),
    sa.Column('prompt_guardrails', sa.Text(), nullable=False),
    sa.Column('unauthorized_message', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_profiles_slug'), 'agent_profiles', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('tool_used', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_preview', sa.String(length=500), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_phone_number'), 'audit_logs', ['phone_number'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_table('authorized_users',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monthly_quota', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('has_all_area_access', sa.Boolean(), nullable=False),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('summary_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorized_users_phone_number'), 'authorized_users', ['phone_number'], unique=True)
    op.create_table('document_blobs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('integration_sources',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('allowed_hosts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auth_type', sa.String(length=30), nullable=False),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('default_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('allow_private_network', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_response_bytes', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_sources_slug'), 'integration_sources', ['slug'], unique=True)
    op.create_table('knowledge_blocks',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_blocks_key'), 'knowledge_blocks', ['key'], unique=True)
    op.create_table('message_statuses',
    sa.Column('meta_message_id', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=120), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('context', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.Column('error_title', sa.String(length=255), nullable=True),
    sa.Column('status_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_statuses_meta_message_id'), 'message_statuses', ['meta_message_id'], unique=True)
    op.create_index(op.f('ix_message_statuses_phone'), 'message_statuses', ['phone'], unique=False)
    op.create_index(op.f('ix_message_statuses_status'), 'message_statuses', ['status'], unique=False)
    op.create_table('organization_areas',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_organization_areas_is_active'), 'organization_areas', ['is_active'], unique=False)
    op.create_table('principals',
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_settings',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('vision_model', sa.String(length=100), nullable=False),
    sa.Column('max_file_bytes', sa.BigInteger(), nullable=False),
    sa.Column('max_batch_bytes', sa.BigInteger(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('chunk_tokens', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap_tokens', sa.Integer(), nullable=False),
    sa.Column('retrieval_top_k', sa.Integer(), nullable=False),
    sa.Column('min_relevance_score', sa.Float(), nullable=False),
    sa.Column('vector_weight', sa.Float(), nullable=False),
    sa.Column('lexical_weight', sa.Float(), nullable=False),
    sa.Column('ocr_enabled', sa.Boolean(), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('worker_last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['admin_roles.key'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_role'), 'admin_users', ['role'], unique=False)
    op.create_table('authorized_user_areas',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['organization_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['authorized_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'area_id', name='uq_authorized_user_area')
    )
    op.create_index(op.f('ix_authorized_user_areas_area_id'), 'authorized_user_areas', ['area_id'], unique=False)
    op.create_index(op.f('ix_authorized_user_areas_user_id'), 'authorized_user_areas', ['user_id'], unique=False)
    op.create_table('channel_identities',
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_subject', name='uq_channel_identity_subject')
    )
    op.create_index(op.f('ix_channel_identities_channel'), 'channel_identities', ['channel'], unique=False)
    op.create_index(op.f('ix_channel_identities_principal_id'), 'channel_identities', ['principal_id'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('external_thread_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('consent_version', sa.String(length=80), nullable=True),
    sa.Column('transcript_consent', sa.Boolean(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'channel', 'external_thread_id', name='uq_chat_conversation_external_thread')
    )
    op.create_index('ix_chat_conversation_principal_updated', 'chat_conversations', ['principal_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_chat_conversations_agent_id'), 'chat_conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_channel'), 'chat_conversations', ['channel'], unique=False)
    op.create_index(op.f('ix_chat_conversations_principal_id'), 'chat_conversations', ['principal_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('tool_used', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['authorized_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_phone_created', 'conversation_messages', ['phone_number', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_phone_number'), 'conversation_messages', ['phone_number'], unique=False)
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('document_folders',
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['organization_areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_folders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'parent_id', 'normalized_name', name='uq_document_folder_sibling')
    )
    op.create_index(op.f('ix_document_folders_area_id'), 'document_folders', ['area_id'], unique=False)
    op.create_index(op.f('ix_document_folders_parent_id'), 'document_folders', ['parent_id'], unique=False)
    op.create_index('uq_document_folder_root', 'document_folders', ['area_id', 'normalized_name'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_table('tool_registry',
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('cost_category', sa.String(length=20), nullable=False),
    sa.Column('handler_path', sa.String(length=200), nullable=True),
    sa.Column('result_type', sa.String(length=30), nullable=False),
    sa.Column('handler_kind', sa.String(length=20), server_default='native', nullable=False),
    sa.Column('http_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_registry_source_id'), 'tool_registry', ['source_id'], unique=False)
    op.create_index(op.f('ix_tool_registry_tool_name'), 'tool_registry', ['tool_name'], unique=True)
    op.create_table('usage_records',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('tokens_estimate', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['authorized_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', 'period_year', 'period_month', name='uq_usage_period')
    )
    op.create_index(op.f('ix_usage_records_phone_number'), 'usage_records', ['phone_number'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('client_message_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tool_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'client_message_id', name='uq_chat_message_client_id')
    )
    op.create_index('ix_chat_message_conversation_created', 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('documents',
    sa.Column('reference_code', sa.String(length=24), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('internal_code', sa.String(length=100), nullable=True),
    sa.Column('responsible', sa.String(length=160), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['document_folders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code')
    )
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_folder_id'), 'documents', ['folder_id'], unique=False)
    op.create_index(op.f('ix_documents_internal_code'), 'documents', ['internal_code'], unique=False)
    op.create_index(op.f('ix_documents_purge_after'), 'documents', ['purge_after'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_table('chat_executions',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('inbound_message_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('output_message_id', sa.UUID(), nullable=True),
    sa.Column('tools_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inbound_message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inbound_message_id')
    )
    op.create_index(op.f('ix_chat_executions_conversation_id'), 'chat_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_executions_request_id'), 'chat_executions', ['request_id'], unique=True)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('blob_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('parser_name', sa.String(length=80), nullable=True),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('extraction_method', sa.String(length=40), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['document_blobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_version_number')
    )
    op.create_index(op.f('ix_document_versions_blob_id'), 'document_versions', ['blob_id'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_is_current'), 'document_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_document_versions_status'), 'document_versions', ['status'], unique=False)
    op.create_index('uq_document_version_current', 'document_versions', ['document_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('document_chunks',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('location_label', sa.String(length=160), nullable=True),
    sa.Column('section_title', sa.String(length=300), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, coalesce(content, ''))", persisted=True), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=False),
    sa.Column('is_retrievable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['organization_areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'ordinal', name='uq_document_chunk_ordinal')
    )
    op.create_index(op.f('ix_document_chunks_area_id'), 'document_chunks', ['area_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('is_retrievable'))
    op.create_index(op.f('ix_document_chunks_is_retrievable'), 'document_chunks', ['is_retrievable'], unique=False)
    op.create_index('ix_document_chunks_retrievable_area', 'document_chunks', ['area_id', 'is_retrievable'], unique=False)
    op.create_index('ix_document_chunks_search_vector', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_version_id'), 'document_chunks', ['version_id'], unique=False)
    op.create_table('document_events',
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('actor_admin_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_events_document_id'), 'document_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_events_event_type'), 'document_events', ['event_type'], unique=False)
    op.create_table('document_ingestion_jobs',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_index(op.f('ix_document_ingestion_jobs_batch_id'), 'document_ingestion_jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_document_ingestion_jobs_locked_at'), 'document_ingestion_jobs', ['locked_at'], unique=False)
    op.create_index(op.f('ix_document_ingestion_jobs_next_attempt_at'), 'document_ingestion_jobs', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_document_ingestion_jobs_status'), 'document_ingestion_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_ingestion_jobs_status'), table_name='document_ingestion_jobs')
    op.drop_index(op.f('ix_document_ingestion_jobs_next_attempt_at'), table_name='document_ingestion_jobs')
    op.drop_index(op.f('ix_document_ingestion_jobs_locked_at'), table_name='document_ingestion_jobs')
    op.drop_index(op.f('ix_document_ingestion_jobs_batch_id'), table_name='document_ingestion_jobs')
    op.drop_table('document_ingestion_jobs')
    op.drop_index(op.f('ix_document_events_event_type'), table_name='document_events')
    op.drop_index(op.f('ix_document_events_document_id'), table_name='document_events')
    op.drop_table('document_events')
    op.drop_index(op.f('ix_document_chunks_version_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_search_vector', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_document_chunks_retrievable_area', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_is_retrievable'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('is_retrievable'))
    op.drop_index(op.f('ix_document_chunks_area_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('uq_document_version_current', table_name='document_versions', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_document_versions_status'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_is_current'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_blob_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_chat_executions_request_id'), table_name='chat_executions')
    op.drop_index(op.f('ix_chat_executions_conversation_id'), table_name='chat_executions')
    op.drop_table('chat_executions')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_purge_after'), table_name='documents')
    op.drop_index(op.f('ix_documents_internal_code'), table_name='documents')
    op.drop_index(op.f('ix_documents_folder_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index('ix_chat_message_conversation_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_phone_number'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_tool_registry_tool_name'), table_name='tool_registry')
    op.drop_index(op.f('ix_tool_registry_source_id'), table_name='tool_registry')
    op.drop_table('tool_registry')
    op.drop_index('uq_document_folder_root', table_name='document_folders', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_index(op.f('ix_document_folders_parent_id'), table_name='document_folders')
    op.drop_index(op.f('ix_document_folders_area_id'), table_name='document_folders')
    op.drop_table('document_folders')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_phone_number'), table_name='conversation_messages')
    op.drop_index('ix_conv_phone_created', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_chat_conversations_principal_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_channel'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_agent_id'), table_name='chat_conversations')
    op.drop_index('ix_chat_conversation_principal_updated', table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_channel_identities_principal_id'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_channel'), table_name='channel_identities')
    op.drop_table('channel_identities')
    op.drop_index(op.f('ix_authorized_user_areas_user_id'), table_name='authorized_user_areas')
    op.drop_index(op.f('ix_authorized_user_areas_area_id'), table_name='authorized_user_areas')
    op.drop_table('authorized_user_areas')
    op.drop_index(op.f('ix_admin_users_role'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('rag_settings')
    op.drop_table('principals')
    op.drop_index(op.f('ix_organization_areas_is_active'), table_name='organization_areas')
    op.drop_table('organization_areas')
    op.drop_index(op.f('ix_message_statuses_status'), table_name='message_statuses')
    op.drop_index(op.f('ix_message_statuses_phone'), table_name='message_statuses')
    op.drop_index(op.f('ix_message_statuses_meta_message_id'), table_name='message_statuses')
    op.drop_table('message_statuses')
    op.drop_index(op.f('ix_knowledge_blocks_key'), table_name='knowledge_blocks')
    op.drop_table('knowledge_blocks')
    op.drop_index(op.f('ix_integration_sources_slug'), table_name='integration_sources')
    op.drop_table('integration_sources')
    op.drop_table('document_blobs')
    op.drop_index(op.f('ix_authorized_users_phone_number'), table_name='authorized_users')
    op.drop_table('authorized_users')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_phone_number'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_profiles_slug'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    op.drop_index(op.f('ix_admin_roles_key'), table_name='admin_roles')
    op.drop_index(op.f('ix_admin_roles_is_active'), table_name='admin_roles')
    op.drop_table('admin_roles')
    # ### end Alembic commands ###
